[package]
name = "rustw"
version = "0.1.0"
authors = ["Nick Cameron <ncameron@mozilla.com>"]

[dependencies]
url = "0.5.7"
hyper = "0.8.0"
getopts = "0.2"
serde = "*"
serde_json = "*"
serde_macros = "*"
