[package]
name = "rustw"
version = "0.1.0"
authors = ["Nick Cameron <ncameron@mozilla.com>"]
build = "build.rs"

[dependencies]
derive-new = "0.3"
url = "0.5"
getopts = "0.2"
rustc-serialize = "0.3"
serde = "0.9"
serde_json = "0.9"
serde_derive = "0.9"
toml = "0.1"
rls-analysis = { git = "https://github.com/nrc/rls-analysis" }
rls-span = { git = "https://github.com/nrc/rls-span" }
rls-vfs = { git = "https://github.com/nrc/rls-vfs" }
log = "0.3"
env_logger = "0.3"

[dependencies.hyper]
version = "0.8"
default-features = false

[build-dependencies]
walkdir = "0.1"
