[package]
name = "rustw"
version = "0.1.0"
authors = ["Nick Cameron <ncameron@mozilla.com>"]
build = "build.rs"

[dependencies]
url = "0.5"
getopts = "0.2"
rustc-serialize = "0.3"
serde = "0.7"
serde_json = "0.7"
serde_macros = "0.7"
toml = "0.1"

[dependencies.hyper]
version = "0.8"
default-features = false

[build-dependencies]
walkdir = "0.1"
